version: '2'

services:

  api:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ".:/api"
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: password